<?php

namespace app\modules\user\models;

/**
 * Class Users
 * @package app\modules\admin\models
 * @property string $backup_email [varchar(255)]  Backup Email (optional)
 * @property string $city_id [integer]  City
 * @property string $country_id [integer]  Country
 */
class Users extends \app\models\Users
{
    public $timeArray = [
        'created_at',
        'updated_at',
        // 'approved_at',
        // 'blocked_at',
    ];

    public function beforeSave($insert)
    {
        foreach ($this->timeArray as $time) {
            if (!empty(!$this->$time)) {
                $this->$time = strtotime($this->$time);
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
